service: wallet-login-triggers

custom:
  USER_POOL_NAME: ${cf:wallet-login-resources-${self:provider.stage}.UserPoolName}
  USER_POOL_ARN: ${cf:wallet-login-resources-${self:provider.stage}.UserPoolArn}

provider:
  name: aws
  runtime: nodejs12.x
  profile: davidlocal

functions:
  createAuthChallenge:
    handler: createAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.USER_POOL_NAME}
          trigger: CreateAuthChallenge
          existing: true
  defineAuthChallenge:
    handler: defineAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.USER_POOL_NAME}
          trigger: DefineAuthChallenge
          existing: true
  preSignUp:
    handler: preSignUp.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.USER_POOL_NAME}
          trigger: PreSignUp
          existing: true
  verifyAuthChallenge:
    handler: verifyAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.USER_POOL_NAME}
          trigger: VerifyAuthChallengeResponse
          existing: true
